# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0015_auto_20180201_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerdashboard',
            name='course_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
