# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 14:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0016_auto_20181009_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationerror',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
