# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0017_userregistrationerror_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationbatch',
            name='activation_file_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationbatch',
            name='error_file_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationbatch',
            name='time_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
