# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 10:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0018_auto_20181101_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationbatch',
            name='triggered_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationbatch',
            name='uploaded_file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
