# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 14:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0019_auto_20181108_1058'),
        ('admin_apros', '0017_learnerdashboardtile_hidden_from_learners'),
    ]

    operations = [
    ]
