# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0020_merge_20181123_1439'),
        ('admin_apros', '0021_userregistrationerror_user_data'),
    ]

    operations = [
    ]
