# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0022_merge_20181127_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomization',
            name='new_ui_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
