# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 04:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0024_auto_20190207_2021_squashed_0028_auto_20190207_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintask',
            name='problem_location',
        ),
        migrations.AddField(
            model_name='admintask',
            name='username',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
