# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-22 16:17


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0025_auto_20190212_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='requested_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
