# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0026_admintask_requested_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomization',
            name='new_ui_enabled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
