# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 07:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0028_add_deletion_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomization',
            name='new_ui_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
