# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0029_auto_20190508_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomization',
            name='is_footer_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
