# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0030_clientcustomization_is_footer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomization',
            name='hide_user_profile',
            field=models.BooleanField(default=False),
        ),
    ]
