# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apros', '0031_clientcustomization_hide_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcustomization',
            name='hide_user_profile',
        ),
        migrations.AddField(
            model_name='clientcustomization',
            name='show_user_profile',
            field=models.BooleanField(default=True),
        ),
    ]
