FORMAT: 1A
HOST: http://api.edx.org

# Open edX API Mock Supplmentals
This is used to supply additional mock results so that we can provide a complete course via the API

### GET /api/groups
 + Response 200 (application/json)
 
     + Body
         
             [
                 {
                     "name": "super_admin",
                     "id":1234,
                     "uri": "http://openedxapi.apiary-mock.com/api/users/14/groups/1234"
                 },
                 {
                     "name": "sub_admin",
                     "id":1357,
                     "uri": "http://openedxapi.apiary-mock.com/api/users/14/groups/1357"
                 },
                 {
                     "name": "company_admin",
                     "id":5678,
                     "uri": "http://openedxapi.apiary-mock.com/api/users/14/groups/5678"
                 },
                 {
                     "name": "arbitrary_group",
                     "id":2468,
                     "uri": "http://openedxapi.apiary-mock.com/api/users/14/groups/2468"
                 }
             ]
             
 

### GET /api/courses/edX/Open_DemoX/edx_demo_course
+ Response 200 (application/json)

    + Body

            {
                "category": "course", 
                "name": "edX Demonstration Course", 
                "modules": [
                    {
                        "category": "chapter", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/d8a6192ade314473a78242dfeedfbf5b", 
                        "id": "i4x:/edX/Open_DemoX/chapter/d8a6192ade314473a78242dfeedfbf5b", 
                        "name": "Introduction"
                    }, 
                    {
                        "category": "chapter", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/interactive_demonstrations", 
                        "id": "i4x:/edX/Open_DemoX/chapter/interactive_demonstrations", 
                        "name": "Example Week 1: Getting Started"
                    }, 
                    {
                        "category": "chapter", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/graded_interactions", 
                        "id": "i4x:/edX/Open_DemoX/chapter/graded_interactions", 
                        "name": "Example Week 2: Get Interactive"
                    }, 
                    {
                        "category": "chapter", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/social_integration", 
                        "id": "i4x:/edX/Open_DemoX/chapter/social_integration", 
                        "name": "Example Week 3: Be Social"
                    }, 
                    {
                        "category": "chapter", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/1414ffd5143b4b508f739b563ab468b7", 
                        "id": "i4x:/edX/Open_DemoX/chapter/1414ffd5143b4b508f739b563ab468b7", 
                        "name": "About Exams and Certificates"
                    }
                ], 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course", 
                "number": "Open_DemoX", 
                "org": "edX", 
                "id": "edX/Open_DemoX/edx_demo_course"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/d8a6192ade314473a78242dfeedfbf5b
+ Response 200 (application/json)

    + Body

            {
                "category": "chapter", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/d8a6192ade314473a78242dfeedfbf5b", 
                "modules": [
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/edx_introduction", 
                        "id": "i4x:/edX/Open_DemoX/sequential/edx_introduction", 
                        "name": "Demo Course Overview"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/chapter/d8a6192ade314473a78242dfeedfbf5b", 
                "name": "Introduction"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/edx_introduction
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/edx_introduction", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_0270f6de40fc", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_0270f6de40fc", 
                        "name": "Introduction: Video and Sequences"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/edx_introduction", 
                "name": "Demo Course Overview"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/interactive_demonstrations
+ Response 200 (application/json)

    + Body

            {
                "category": "chapter", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/interactive_demonstrations", 
                "modules": [
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/19a30717eff543078a5d94ae9d6c18a5", 
                        "id": "i4x:/edX/Open_DemoX/sequential/19a30717eff543078a5d94ae9d6c18a5", 
                        "name": "Lesson 1 - Getting Started"
                    }, 
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/basic_questions", 
                        "id": "i4x:/edX/Open_DemoX/sequential/basic_questions", 
                        "name": "Homework - Question Styles"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/chapter/interactive_demonstrations", 
                "name": "Example Week 1: Getting Started"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/19a30717eff543078a5d94ae9d6c18a5
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/19a30717eff543078a5d94ae9d6c18a5", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/867dddb6f55d410caaa9c1eb9c6743ec", 
                        "id": "i4x:/edX/Open_DemoX/vertical/867dddb6f55d410caaa9c1eb9c6743ec", 
                        "name": "Getting Started"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/4f6c1b4e316a419ab5b6bf30e6c708e9", 
                        "id": "i4x:/edX/Open_DemoX/vertical/4f6c1b4e316a419ab5b6bf30e6c708e9", 
                        "name": "Working with Videos"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/3dc16db8d14842e38324e95d4030b8a0", 
                        "id": "i4x:/edX/Open_DemoX/vertical/3dc16db8d14842e38324e95d4030b8a0", 
                        "name": "Videos on edX"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/f0e6d90842c44cc7a50fd1a18a7dd982", 
                        "id": "i4x:/edX/Open_DemoX/vertical/f0e6d90842c44cc7a50fd1a18a7dd982", 
                        "name": "Video Demonstrations"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/256f17a44983429fb1a60802203ee4e0", 
                        "id": "i4x:/edX/Open_DemoX/vertical/256f17a44983429fb1a60802203ee4e0", 
                        "name": "Video Presentation Styles"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/e3601c0abee6427d8c17e6d6f8fdddd1", 
                        "id": "i4x:/edX/Open_DemoX/vertical/e3601c0abee6427d8c17e6d6f8fdddd1", 
                        "name": "Interactive Questions"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/134df56c516a4a0dbb24dd5facef746e", 
                        "id": "i4x:/edX/Open_DemoX/vertical/134df56c516a4a0dbb24dd5facef746e", 
                        "name": "Reading Assignments"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/19a30717eff543078a5d94ae9d6c18a5", 
                "name": "Lesson 1 - Getting Started"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/basic_questions
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/basic_questions", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/2152d4a4aadc4cb0af5256394a3d1fc7", 
                        "id": "i4x:/edX/Open_DemoX/vertical/2152d4a4aadc4cb0af5256394a3d1fc7", 
                        "name": "Pointing on a Picture"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/47dbd5f836544e61877a483c0b75606c", 
                        "id": "i4x:/edX/Open_DemoX/vertical/47dbd5f836544e61877a483c0b75606c", 
                        "name": "Drag and Drop"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/54bb9b142c6c4c22afc62bcb628f0e68", 
                        "id": "i4x:/edX/Open_DemoX/vertical/54bb9b142c6c4c22afc62bcb628f0e68", 
                        "name": "Multiple Choice Questions"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_0c92347a5c00", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_0c92347a5c00", 
                        "name": "Mathematical Expressions"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_1fef54c2b23b", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_1fef54c2b23b", 
                        "name": "Chemical Equations"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/2889db1677a549abb15eb4d886f95d1c", 
                        "id": "i4x:/edX/Open_DemoX/vertical/2889db1677a549abb15eb4d886f95d1c", 
                        "name": "Numerical Input"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/e8a5cc2aed424838853defab7be45e42", 
                        "id": "i4x:/edX/Open_DemoX/vertical/e8a5cc2aed424838853defab7be45e42", 
                        "name": "Text input"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/basic_questions", 
                "name": "Homework - Question Styles"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/graded_interactions
+ Response 200 (application/json)

    + Body

            {
                "category": "chapter", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/graded_interactions", 
                "modules": [
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/simulations", 
                        "id": "i4x:/edX/Open_DemoX/sequential/simulations", 
                        "name": "Lesson 2 - Let's Get Interactive!"
                    }, 
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/graded_simulations", 
                        "id": "i4x:/edX/Open_DemoX/sequential/graded_simulations", 
                        "name": "Homework - Labs and Demos"
                    }, 
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/machine_grading", 
                        "id": "i4x:/edX/Open_DemoX/sequential/machine_grading", 
                        "name": "Homework - Essays"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/chapter/graded_interactions", 
                "name": "Example Week 2: Get Interactive"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/simulations
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/simulations", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/d0d804e8863c4a95a659c04d8a2b2bc0", 
                        "id": "i4x:/edX/Open_DemoX/vertical/d0d804e8863c4a95a659c04d8a2b2bc0", 
                        "name": "Lesson 2 - Let's Get Interactive! "
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_2dbb0072785e", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_2dbb0072785e", 
                        "name": "An Interactive Reference Table"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_98cf62510471", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_98cf62510471", 
                        "name": "Zooming Diagrams"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_d32bf9b2242c", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_d32bf9b2242c", 
                        "name": "Electronic Sound Experiment"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/simulations", 
                "name": "Lesson 2 - Let's Get Interactive!"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/graded_simulations
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/graded_simulations", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/d6cee45205a449369d7ef8f159b22bdf", 
                        "id": "i4x:/edX/Open_DemoX/vertical/d6cee45205a449369d7ef8f159b22bdf", 
                        "name": "Labs and Demos"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_0fab6aa52165", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_0fab6aa52165", 
                        "name": "Molecule Editor"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_aae927868e55", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_aae927868e55", 
                        "name": "Code Grader"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_c037f3757df1", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_c037f3757df1", 
                        "name": "Electric Circuit Simulator"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_bc69a47c6fae", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_bc69a47c6fae", 
                        "name": "Protein Creator"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/graded_simulations", 
                "name": "Homework - Labs and Demos"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/machine_grading
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/machine_grading", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/72a7649a078b43a3bc539d62ef145f87", 
                        "id": "i4x:/edX/Open_DemoX/vertical/72a7649a078b43a3bc539d62ef145f87", 
                        "name": "Welcome to Essays!"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/1938e21ae6654571806a8e129fbda730", 
                        "id": "i4x:/edX/Open_DemoX/vertical/1938e21ae6654571806a8e129fbda730", 
                        "name": "Self-Assessed Essay"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_ce1a91955d1f", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_ce1a91955d1f", 
                        "name": "Feedback and AI-\"Graded\" Essays"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/c2ad8729f7aa4e429f72bc03ecf96e3d", 
                        "id": "i4x:/edX/Open_DemoX/vertical/c2ad8729f7aa4e429f72bc03ecf96e3d", 
                        "name": "Peer-Graded Essay"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/fd86ec5f942542349b791acb880e704a", 
                        "id": "i4x:/edX/Open_DemoX/vertical/fd86ec5f942542349b791acb880e704a", 
                        "name": "Combined Assessment"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/85398281cb7741849d5bbb7d5abe34d8", 
                        "id": "i4x:/edX/Open_DemoX/vertical/85398281cb7741849d5bbb7d5abe34d8", 
                        "name": "Sample Answers"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/machine_grading", 
                "name": "Homework - Essays"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/social_integration
+ Response 200 (application/json)

    + Body

            {
                "category": "chapter", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/social_integration", 
                "modules": [
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/48ecb924d7fe4b66a230137626bfa93e", 
                        "id": "i4x:/edX/Open_DemoX/sequential/48ecb924d7fe4b66a230137626bfa93e", 
                        "name": "Lesson 3 - Be Social"
                    }, 
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/dbe8fc027bcb4fe9afb744d2e8415855", 
                        "id": "i4x:/edX/Open_DemoX/sequential/dbe8fc027bcb4fe9afb744d2e8415855", 
                        "name": "Homework - Find Your Study Buddy"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/chapter/social_integration", 
                "name": "Example Week 3: Be Social"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/48ecb924d7fe4b66a230137626bfa93e
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/48ecb924d7fe4b66a230137626bfa93e", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/3c4b575924bf4b75a2f3542df5c354fc", 
                        "id": "i4x:/edX/Open_DemoX/vertical/3c4b575924bf4b75a2f3542df5c354fc", 
                        "name": "Be Social"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_3888db0bc286", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_3888db0bc286", 
                        "name": "Discussion Forums"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/312cb4faed17420e82ab3178fc3e251a", 
                        "id": "i4x:/edX/Open_DemoX/vertical/312cb4faed17420e82ab3178fc3e251a", 
                        "name": "Getting Help"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/48ecb924d7fe4b66a230137626bfa93e", 
                "name": "Lesson 3 - Be Social"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/dbe8fc027bcb4fe9afb744d2e8415855
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/dbe8fc027bcb4fe9afb744d2e8415855", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/26d89b08f75d48829a63520ed8b0037d", 
                        "id": "i4x:/edX/Open_DemoX/vertical/26d89b08f75d48829a63520ed8b0037d", 
                        "name": "Homework - Find Your Study Buddy"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/dbe8fc027bcb4fe9afb744d2e8415855", 
                "name": "Homework - Find Your Study Buddy"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/1414ffd5143b4b508f739b563ab468b7
+ Response 200 (application/json)

    + Body

            {
                "category": "chapter", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/chapter/1414ffd5143b4b508f739b563ab468b7", 
                "modules": [
                    {
                        "category": "sequential", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/workflow", 
                        "id": "i4x:/edX/Open_DemoX/sequential/workflow", 
                        "name": "edX Exams"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/chapter/1414ffd5143b4b508f739b563ab468b7", 
                "name": "About Exams and Certificates"
            }

### GET /api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/workflow
+ Response 200 (application/json)

    + Body

            {
                "category": "sequential", 
                "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/sequential/workflow", 
                "modules": [
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/934cc32c177d41b580c8413e561346b3", 
                        "id": "i4x:/edX/Open_DemoX/vertical/934cc32c177d41b580c8413e561346b3", 
                        "name": "EdX Exams"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_f04afeac0131", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_f04afeac0131", 
                        "name": "Immediate Feedback"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/b6662b497c094bcc9b870d8270c90c93", 
                        "id": "i4x:/edX/Open_DemoX/vertical/b6662b497c094bcc9b870d8270c90c93", 
                        "name": "Getting Answers"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/f91d8d31f7cf48ce990f8d8745ae4cfa", 
                        "id": "i4x:/edX/Open_DemoX/vertical/f91d8d31f7cf48ce990f8d8745ae4cfa", 
                        "name": "Answering More Than Once"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_ac391cde8a91", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_ac391cde8a91", 
                        "name": "Limited Checks"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/vertical_36e0beb03f0a", 
                        "id": "i4x:/edX/Open_DemoX/vertical/vertical_36e0beb03f0a", 
                        "name": "Randomized Questions"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/1b0e2c2c84884b95b1c99fb678cc964c", 
                        "id": "i4x:/edX/Open_DemoX/vertical/1b0e2c2c84884b95b1c99fb678cc964c", 
                        "name": "Overall Grade Performance"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/c7e98fd39a6944edb6b286c32e1150ff", 
                        "id": "i4x:/edX/Open_DemoX/vertical/c7e98fd39a6944edb6b286c32e1150ff", 
                        "name": "Passing a Course"
                    }, 
                    {
                        "category": "vertical", 
                        "uri": "http://openedxapi.apiary-mock.com/api/courses/edX/Open_DemoX/edx_demo_course/modules/i4x:/edX/Open_DemoX/vertical/d6eaa391d2be41dea20b8b1bfbcb1c45", 
                        "id": "i4x:/edX/Open_DemoX/vertical/d6eaa391d2be41dea20b8b1bfbcb1c45", 
                        "name": "Getting Your edX Certificate"
                    }
                ], 
                "id": "i4x:/edX/Open_DemoX/sequential/workflow", 
                "name": "edX Exams"
            }

