version: 2
jobs:
  build:
    working_directory: ~/mckinseyacademy/mcka_apros
    parallelism: 1
    docker:
        - image: circleci/python:2.7
        - image: mysql:5.6
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: ''

    steps:
        - checkout

        - restore_cache:
            key: dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}

        - run:
            name: Creating virtual environment
            command: virtualenv ~/virtualenvs/venv && source ~/virtualenvs/venv/bin/activate

        - run:
            name: Installing requirements
            command: |
                source ~/virtualenvs/venv/bin/activate
                pip install -r requirements.txt --exists-action w
                pip install -r test-requirements.txt
        
        - save_cache:
            key: dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
            paths:
                - ~/virtualenvs/venv

        - run:
            name: Wait for DB
            command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

        - run:
            name: Run Coverage and Upload Codecov
            command: |
                source ~/virtualenvs/venv/bin/activate
                coverage run --source='.' manage.py test --settings=mcka_apros.test_settings
                coverage xml
                bash <(curl -s https://codecov.io/bash) -y codecov.yml
        
        - run:
            name: Check flake8 quality violations
            command: |
                source ~/virtualenvs/venv/bin/activate
                flake8 ./
