# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 08:57


import certificates.models
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20170929_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='course_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template',
            field=models.TextField(verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='certificatetemplateasset',
            name='asset',
            field=models.FileField(max_length=255, upload_to=certificates.models.template_assets_path, validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'text/css', 'text/plain', 'application/javascript'])], verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='certificatetemplateasset',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
