# Generated by Django 2.2.9 on 2020-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191010_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
