# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 08:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181009_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedcontentitem',
            name='sequence',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='curatedcontentitem',
            index_together=set([('course_id', 'content_type')]),
        ),
    ]
