# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 20:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='lesson_label',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureflags',
            name='progress_indication',
            field=models.BooleanField(default=True),
        ),
    ]
