# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180926_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
