# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 10:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_featureflags_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemetadata',
            name='lessons_label',
            field=jsonfield.fields.JSONField(default={b'few': b'', b'many': b'', b'one': b'', b'other': b'', b'two': b'', b'zero': b''}),
        ),
        migrations.AddField(
            model_name='coursemetadata',
            name='modules_label',
            field=jsonfield.fields.JSONField(default={b'few': b'', b'many': b'', b'one': b'', b'other': b'', b'two': b'', b'zero': b''}),
        ),
    ]
