# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 10:38


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_featureflags_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemetadata',
            name='lessons_label',
            field=jsonfield.fields.JSONField(default={'few': '', 'many': '', 'one': '', 'other': '', 'two': '', 'zero': ''}),
        ),
        migrations.AddField(
            model_name='coursemetadata',
            name='modules_label',
            field=jsonfield.fields.JSONField(default={'few': '', 'many': '', 'one': '', 'other': '', 'two': '', 'zero': ''}),
        ),
    ]
