# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 10:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20181017_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='enable_enhanced_caching',
            field=models.BooleanField(default=False),
        ),
    ]
