# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_featureflags_enable_enhanced_caching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureflags',
            old_name='enable_enhanced_caching',
            new_name='enhanced_caching',
        ),
    ]
