# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20181023_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureflags',
            name='leaderboard',
        ),
    ]
