# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 06:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_featureflags_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureflags',
            old_name='cohort_map',
            new_name='leaderboard',
        ),
    ]
