# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190503_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='show_ld_discovery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureflags',
            name='show_ld_logo',
            field=models.BooleanField(default=False),
        ),
    ]
