# Generated by Django 2.2.11 on 2020-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190905_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='extend_session_on_video',
            field=models.BooleanField(default=False),
        ),
    ]
