# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='licensegrant',
            index_together=set([('granted_id', 'grantee_id')]),
        ),
    ]
